### ISSUE TITLE
Charts don't show up

### ISSUE THREAD

**Issue by pyongjoo** [pseudoinverse/createLab#1]
I just downloaded and started the app with the following commands:
```
rm package-lock.json
npm install
npm start
```

My Chrome console shows the following error:

<img width="728" alt="Screen Shot 2022-01-19 at 5 11 12 PM" src="https://user-images.githubusercontent.com/1316874/150233190-48d171d3-ca25-4ebb-b8b5-ae3cedc4e5c9.png">

**Comment by pseudoinverse** [comment]
I've updated the code and there should be no errors and warnings for now.

Also make sure to start the backend server by

```
cd backend
python3 simulator.py
```

before running any simulations.
